- name: Reload systemd units
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart rootless containerd user service
  ansible.builtin.systemd_service:
    name: containerd.service
    scope: user
    state: restarted
    daemon_reload: true
  become_user: "{{ nerdctl_user }}"
